image: docker:20.10.12

services:
  - docker:20.10.12-dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

stages:
  - build
  - test
  - deploy

# Этап сборки
build:
  stage: build
  script:
    # Переход в директорию проекта
    - cd multi-module-service/cmd/mainapp
    # Компиляция приложения (если это Go, используйте go build)
    - go build -o .
    # Проверка собранного бинарного файла
    - ./mainapp --help

# Этап тестирования
test:
  stage: test
  script:
    - cd multi-module-service
    # Запуск тестов для всех пакетов проекта
    - go test ./... -v

# Этап деплоя (настраивается под ваши нужды)
deploy:
  stage: deploy
  script:
    - echo "Deployment step. Add your deployment script here."
