image: "golang:1.20"

stages:
  - build
  # - test
  - deploy

before_script:
  - go version
  - apt-get update -qq && apt-get install -y -qq libsystemd-dev
  - apt-get install -y libpulse0 libpulse-dev

# Этап сборки
build:
  stage: build
  script:
    # Диагностика текущей директории и файлов
    - echo "Current directory and files:"
    - pwd
    - ls -R
    # Переход в директорию проекта
    - cd cmd/mainapp || exit 1
    # Компиляция приложения (если это Go, используйте go build)
    - go build -o mainapp .
    # Проверка собранного бинарного файла
    - ./mainapp --help

# Этап тестирования
# test:
#   stage: test
#   script:
#     - cd multi-module-service
#     # Запуск тестов для всех пакетов проекта
#     - go test ./... -v

# Этап деплоя
deploy:
  stage: deploy
  script:
    - echo "Deployment step. Add your deployment script here."
